MAIN_MENU = 'Выберите меню'
ASK_TRACKING_NUMBER = 'Введите номер отправления'
TRACKING_NOTIFICATION_SUBSCRIPTION = 'Хотите автоматически получать уведомления по отправлению %s?'
SUBSCRIPTION_SUCCESSFUL = 'Подписка успешно оформлена!'
TRACKING_NOTIFICATION_SUBSCRIPTION_WITH_PHONE = 'Хотите отслеживать все отправления, которые привязаны к этому номеру телефона?'
ASK_ANOTHER_TRACKING_NUMBER = 'Введите другой номер отправления или нажмите "Назад" чтобы попасть в главное меню.'

EXCEPTION_MESSAGE = 'Ой! Случилась непредвиденная ошибка! Наши специалисты уже решают эту проблему.'
INCORRECT_TRACKING_NUMBER = 'Неверный формат номера отправления'
TRACKING_NOT_FOUND = 'По вашему запросу ничего не найдено.'
TRACKING_STATUS_CHANGED = 'Статус отправления {0} изменился на "*{1}*"'
TRACKING_LIST_CHANGED = 'Изменился список отправлений! Теперь остлеживаются следующие посылки: %s'